### PR TITLE
Accessibility fixes: keyboard navigation to city, and checkbox labels

### LINKED ISSUE #350: City links not interactive via keyboard
Keyboard navigation within the grid works fine, but interactive elements inside grid cells by default cannot be reached. They can be clicked by mouse, but are not triggered when hitting Enter, thus we are excluding people who cannot use a mouse.

There are examples of managing focus within cells in the AgGrid docs, but nothing about how to allow events to propagate to child elements. It's pretty annoying that AgGrid hasn't implemented any built-in config setting to allow keyboard events to propagate, but we can do it ourselves:
https://github.com/ag-grid/ag-grid/issues/4114#issuecomment-1517089053

Idea is to add a keyboard listener to the enclosing grid cell element for the Enter key, while allowing mouse click events to work as normal. With a useEffect, we can add the listener on mount and remove it on unmount. Simples... though I've not tried it out yet 🍀

### PR DESCRIPTION
**Pull request by chriswilty**
I noted that it isn't possible to navigate to single city view using keyboard (Enter key), which excludes all those who are unable to use mouse.

This PR addresses that, while also correcting another accessibility issue in which checkboxes were not associated with their label.

I have also tested these changes using NVDA screen reader, and they work as expected.

resolves #350

### CODE REVIEW

**Review by Ben-EJ — APPROVED** [review]
LGTM

**Comment by chriswilty** [comment]
Note: this PR is awaiting the fix in #352

**Comment by chriswilty** [comment]
I probably need to sync my fork and re-push this one, to get the build checks passing.

**Comment by chriswilty** [comment]
For what it's worth, the jest coverage report has a heap of false negatives, as you are largely using Testing Library to test user interactions rather than directly testing function logic inside components. Testing by user interaction is definitely the recommended way to test dynamic components, but you may want to look into configuring the coverage report to more accurately reflect this testing strategy.

**Comment by sebsteinig** [comment]
Thank you so much for your work on this and updating the PR, Chris! This is hugely appreciated. I am merging and deploying the changes now. Please note, that we are also switching to a new production sever, so the updated UI will be available at http://136.156.139.13

**Review by sebsteinig — APPROVED** [review]

**Pull request merged**
